services:
  mysql:
    container_name: mysql
    image: mysql:8.4.10@sha256:d36d39a64cd12a5c1cc9e6aa2bfb5f8d4c81a2f6586e0a04a9ae13939db02209
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - prestashop_network

  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:9.2.x-apache@sha256:e0cb721d4513066852b3db1eb2dcf8d7f1adbd6a83e2708008e4a7560dd73df4
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "8080:80"
    environment:
      DB_SERVER: mysql
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_ROOT_PASSWORD}
      PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
      PS_FOLDER_ADMIN: admin-dev
      PS_FOLDER_INSTALL: install-old
      PS_DEV_MODE: 1
    networks:
      - prestashop_network
    volumes:
      - ./binshopsrest:/var/www/html/modules/binshopsrest

volumes:
  db_data:

networks:
  prestashop_network: