name: PrestaShop Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  prestashop-tester:
    runs-on: ubuntu-latest    

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Python 3.14
        uses: actions/setup-python@v7
        with:
          python-version: "3.14"
          cache: "pip"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Get Playwright version
        id: playwright-version
        run: echo "version=$(playwright --version)" >> "$GITHUB_OUTPUT"

      - name: Cache Playwright Browsers
        uses: actions/cache@v6
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-all-${{ steps.playwright-version.outputs.version }}

      - name: Install All Playwright Browsers & OS Dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: playwright install --with-deps

      - name: Install OS Dependencies (Cache Hit)
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: playwright install-deps

      - name: Checkout Binshops REST module
        uses: actions/checkout@v7
        with:
          repository: 'binshops/prestashop-rest'
          ref: 'c9007fbff64daed488a51267ff66fb9bf903c41f'
          path: 'binshopsrest'

      - name: Run Pytest Suite
        run: |          
          export DB_ROOT_PASSWORD=$(openssl rand -hex 16)
          pytest -n auto --browser chromium --browser firefox --browser webkit --reruns 2 --reruns-delay 1 --screenshot=only-on-failure --output=screenshots       
        env:
          CI: "true"
          BASE_URL: "http://localhost:8080/"
          DB_NAME: "prestashop"
          DB_USER: "root"

      - name: Upload Pytest HTML Report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: pytest-html-report
          archive: false
          path: reports/report.html
          retention-days: 30

      - name: Capture Docker Logs on Failure
        if: failure()
        run: |
          mkdir -p logs
          docker compose logs > logs/docker-compose-debug.log

      - name: Upload Docker Debug Logs
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          archive: false
          name: docker-debug-logs
          path: logs/
      
      - name: Upload Failure Screenshots
        if: failure()
        uses: actions/upload-artifact@v7
        with:
          name: playwright-failure-screenshots
          path: screenshots/
          retention-days: 14
